import {equal,type Language,type TestCase,type Result} from './problem';
export async function runCode(code:string,language:Language,tests:TestCase[],comparison:string,signal?:AbortSignal):Promise<Result[]>{
if(code.length>30000)throw new Error('Code is limited to 30,000 characters.');if(tests.length>80)throw new Error('At most 80 cases per run.');
const response=await fetch('/runner-worker.js',{signal});if(!response.ok)throw new Error('Runner unavailable.');const workerSource=await response.text();
return new Promise((resolve,reject)=>{const frame=document.createElement('iframe');frame.sandbox.add('allow-scripts');frame.src='/api/runner';frame.hidden=true;frame.title='Isolated code runner';const channel=new MessageChannel();let timer:ReturnType<typeof setTimeout>;let finished=false;
const cleanup=()=>{clearTimeout(timer);channel.port1.close();frame.remove();signal?.removeEventListener('abort',abort)};
const fail=(message:string)=>{if(finished)return;finished=true;cleanup();reject(new Error(message))};const abort=()=>fail('Execution stopped.');signal?.addEventListener('abort',abort,{once:true});if(signal?.aborted){abort();return;}
const timeout=(ms:number,message:string)=>{clearTimeout(timer);timer=setTimeout(()=>fail(message),ms)};
channel.port1.onmessage=({data})=>{if(finished)return;if(data.type==='connected')channel.port1.postMessage({type:'init',language,workerSource});if(data.type==='ready'){timeout(5000,'Time limit exceeded (5 seconds for the test batch).');channel.port1.postMessage({type:'run',language,code,tests});}if(data.type==='error')fail(data.error);if(data.type==='result'){if(!Array.isArray(data.results)||data.results.length!==tests.length){fail('Invalid runner response.');return}finished=true;cleanup();resolve(data.results.map((r:Result,i:number)=>({...r,expected:tests[i].expected,passed:!r.error&&equal(r.actual,tests[i].expected,comparison)})));}};
frame.onload=()=>frame.contentWindow?.postMessage({type:'connect'},'*',[channel.port2]);document.body.appendChild(frame);timeout(60000,'Python runtime download timed out. Check your connection and retry.');});}
